### ISSUE TITLE
UNHANDLED REJECTION Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by masihomid** [christiandavid/gatsby-theme-byfolio#2]
Hi Chris
Thank you so much for making this site a gatsby theme. I am trying to build my portfolio using this however face the below error when run "gastby develop"

success open and validate gatsby-configs - 0.214s
success load plugins - 13.293s
success onPreInit - 0.187s
success initialize cache - 0.086s
success copy gatsby files - 0.677s
success onPreBootstrap - 0.056s
success createSchemaCustomization - 0.007s
success source and transform nodes - 0.290s
success building schema - 0.663s
success createPages - 0.051s
success createPagesStatefully - 0.151s
success onPreExtractQueries - 0.003s
success update schema - 0.037s
success extract queries from components - 1.179s
success write out requires - 0.136s
success write out redirect data - 0.036s
⠋ onPostBootstrap
⠋ Build manifest and related icons

 ERROR

UNHANDLED REJECTION Cannot read property 'match' of undefined

  TypeError: Cannot read property 'match' of undefined

  - api-runner-node-error-parser.js:39 errorParser
    [masih-portfolio]/[gatsby]/dist/utils/api-runner-node-error-parser.js:39:33

  - api-runner-node.js:398
    [masih-portfolio]/[gatsby]/dist/utils/api-runner-node.js:398:29

  - api-runner-node.js:340 async module.exports
    [masih-portfolio]/[gatsby]/dist/utils/api-runner-node.js:340:18

  - index.js:507 async module.exports
    [masih-portfolio]/[gatsby]/dist/bootstrap/index.js:507:3

  - develop.js:407 async module.exports
    [masih-portfolio]/[gatsby]/dist/commands/develop.js:407:7
⠋ onPostBootstrap
⠋ Build manifest and related icons

I have put my source at https://github.com/darKoub/byfolio 

Thank you.

**Comment by christiandavid** [comment]
Hi, you're welcome
Did you follow the installation guide? 
As soon as I get a time frame I'll check it out

**Comment by masihomid** [comment]
yes , I did follow that. Not sure what i missed. Thank you.

**Comment by christiandavid** [comment]
In the **images/skills** folder there is a missing image, to fix this problem you must duplicate any of the files and rename it as **graphql.png** this should look something like this **images/skills/graphql.png** after you do this it will work, I will leave this here to correct this problem later

Thank you for notifying me

**Comment by aswanth9495** [comment]
I have the same directory structure and configurations as of @darKoub . But I'm getting this error.
![Screenshot 2020-01-24 at 2 00 06 PM](https://user-images.githubusercontent.com/59434647/73055068-f512b980-3eb1-11ea-9c15-5d14241232d7.png)
Please help me with this.

**Comment by christiandavid** [comment]
@aswanth9495  could you create the issue using the appropriate template?
Just like @darKoub did. Thanks

**Comment by christiandavid** [comment]
@darKoub following the recommendation I left you in my second last comment fixed the problem?

**Comment by masihomid** [comment]
> In the **images/skills** folder there is a missing image, to fix this problem you must duplicate any of the files and rename it as **graphql.png** this should look something like this **images/skills/graphql.png** after you do this it will work, I will leave this here to correct this problem later
> 
> Thank you for notifying me

Hi Chris 

Thanks for look into this. I was away and today got a chance to test it. It still has the same issue. I also tested it on Netlify and got the same error(below):

```
8:55:33 PM: error Cannot read property 'match' of undefined
8:55:33 PM: 
8:55:33 PM:   TypeError: Cannot read property 'match' of undefined
8:55:33 PM:   
8:55:33 PM:   - api-runner-node-error-parser.js:39 errorParser
8:55:33 PM:     [repo]/[gatsby]/dist/utils/api-runner-node-error-parser.js:39:33
8:55:33 PM:   
8:55:33 PM:   - api-runner-node.js:398 Promise.catch.err
8:55:33 PM:     [repo]/[gatsby]/dist/utils/api-runner-node.js:398:29
8:55:33 PM:   
8:55:33 PM: 
8:55:33 PM: not finished onPostBootstrap - 0.078s
```
My new code is https://github.com/darKoub/byfolio

Thank you so much!

**Comment by christiandavid** [comment]
Hi @darKoub , Thanks to you for reporting the problem, I've been a little busy because of my new job, sorry for the delay, I just found the problem and it's due to the internal configuration for the `gatsby-plugin-manifest` plugin, it refers to the `icon.png` file which is resolved in the path `${imagesPath}icon.png`, in short **for the moment just add the icon.png** file inside the folder you used for images **`src/images/icon.png`**, after that the error will not appear again and you can continue with the development of your portfolio
