### ISSUE TITLE
Latest dev build lives in top 15% of browser

### ISSUE THREAD

**Issue by ghost** [christiandavid/gatsby-theme-byfolio#4]
MacOS latest
Firefox latest

Confirmed working properly on Brave (latest) and Safari (latest build as well). 

The entire app is crammed into the top 15% of the page on firefox.

**Comment by christiandavid** [comment]
Hi @Zohvek , the issue is not clear, I would appreciate it if you could create it using the template adding detail about what happens

Thank you
