### ISSUE TITLE
Forced to set all socials (impossible to only set the ones we want)

### ISSUE THREAD

**Issue by nicofeals** [christiandavid/gatsby-theme-byfolio#5]
Hey, I'm new to GatsbyJS, and I discovered your plugin via reddit. It's amazing, thanks for providing it.

Anyway, I'm trying to build my portfolio using your theme, and it seems like you have to provide an url for all socials?
For example, if in the config I have
```
plugins: [
    {
        resolve: `@christiandavid/gatsby-theme-byfolio`,
        options: {
            ...
            social: {
                // Usernames
                gitHub: `nicofeals`,
                linkedIn: `in/nicolasceccarello/`,
            },
            ...
        }
    }
]
```
I get an error when compiling it
```
There was an error in your GraphQL query:

Cannot query field "twitter" on type "SiteSiteMetadataSocial".
```
From what I understand, I guess that's how gatsby works and all fields should be set.

First, my question is, is it indeed a gatsby related problem, or is it specific to the theme?
And isn't there a workaround that'd allow to only set the socials you want to provide (or simply the one you have)?

Thanks a lot

**Comment by christiandavid** [comment]
Hi, I just saw this message, as soon as I have time I will review what you said, if you could share the link to your portfolio it would be easier to identify the problem

Thank you
