### ISSUE TITLE
The site incorrect work on Firefox

### ISSUE THREAD

**Issue by leonidkuznetsov18** [christiandavid/gatsby-theme-byfolio#8]
1. 
![image](https://user-images.githubusercontent.com/9495532/82027797-77133200-969d-11ea-9c01-d4e1d00746a8.png)

2. 
![image](https://user-images.githubusercontent.com/9495532/82027828-809c9a00-969d-11ea-97f6-479541745110.png)

3. 
![image](https://user-images.githubusercontent.com/9495532/82027873-8eeab600-969d-11ea-9641-afee06f2132c.png)

This problem happens because your height is not 100% in Firefox

**Comment by grimmie38** [comment]
Hi @MrChe 
How did you resolve these three issues? 👩‍🦱

**Comment by leonidkuznetsov18** [comment]
Yes, this problem with height is styles

**Comment by christiandavid** [comment]
Thank you @MrChe for reporting the problem
