### ISSUE TITLE
Bug when user switch between links

### ISSUE THREAD

**Issue by leonidkuznetsov18** [christiandavid/gatsby-theme-byfolio#9]
STR:
1. Click to the hamburger menu
2. Click to Menu item 
3. Open terminal
![image](https://user-images.githubusercontent.com/9495532/82044324-d2e9b500-96b5-11ea-8978-d272255e6378.png)

**Comment by grimmie38** [comment]
Similar **issue** I have.
If I want to go to another page, it shows blank page. The chrome console shows this.

![image](https://user-images.githubusercontent.com/55588335/82116398-d9a72380-97ac-11ea-8d40-cb473cecfc1b.png)

**Comment by leonidkuznetsov18** [comment]
for the fix, this bug needs to install package `gsap`. 
`npm i -D gsap`

**Comment by grimmie38** [comment]
Hey MrChe, it works like a magic! Thank you.
In addition, can you please explain the reason why I need gsap for those issues?

**Comment by christiandavid** [comment]
Thank you @MrChe and @tkcong I just solved it
